### ISSUE TITLE
KeyError: 'name_temp'

### ISSUE THREAD

**Issue by Hawk-3** [SzenProgs/elehant_meter#1]
Добрый день. На чистой установке HA 
 Home Assistant 2023.4.6 Supervisor 2023.05.dev0201 Пользовательский интерфейс 20230411.1 - latest 

Такая вот ошибка:
![Снимок экрана от 2023-05-03 18-22-01](https://user-images.githubusercontent.com/64266629/235963041-aa9c93c3-d998-4a5a-80d0-04bb05b25967.png)

```Logger: homeassistant.components.sensor
Source: custom_components/elehant_water/sensor.py:167
Integration: Сенсор (documentation, issues)
First occurred: 18:17:50 (1 occurrences)
Last logged: 18:17:50

Error while setting up elehant_water platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/elehant_water/sensor.py", line 167, in setup_platform
    ha_entities.append(WaterTempSensor(device["id"], device["name_temp"]))
KeyError: 'name_temp'
```

**Comment by SzenProgs** [comment]
Это нерабочий код. Начал было полноценную разработку компонента с использованием нативных методов HASS, поддержкой добавления счетчиков из интерфейса и их автоматическим определением. Но времени пока нету, к сожалению.
Рекомендую использовать мой форк https://github.com/SzenProgs/elehant_water

**Comment by Hawk-3** [comment]
А! Сорри! Конфиг неправильно сделал.
Забыл name_temp: и water_type:

(форк и использую)
